name: flutter_date_pickers
description: Flutter package for day, week, range and month date pickers.
version: 0.4.2
homepage: https://github.com/MariaMelnik/flutter_date_pickers
issue_tracker: https://github.com/MariaMelnik/flutter_date_pickers/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.17.0 <1.0.0"
  flutter_localizations:
    sdk: flutter
  week_number: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
